export enum ConstanthPathEnum {
  HOME_PAGE = '/',
  SIGN_IN = '/sign-in',
  SIGN_UP = '/sign-up',
  PRODUCT_SHOP = '/products/:product_id',
  PRODUCT_DETAIL = '/products/:product_id/shops/:shop_id',
  PRODUCT_CATEGORY = '/products/categories/:category_name',
  PRODUCT_SEARCH = '/products/search/:search_input',
  COMPANY_LIST = '/companies',
  ADMIN_PRODUCT = '/admin/products',
  ADMIN_PRODUCT_ADD = '/admin/products/add',
  ADMIN_PRODUCT_DETAIL = '/admin/products/:product_id',
  ADMIN_CATEGORY = '/admin/categories',
  ADMIN_SHOP = '/admin/shops',
  ADMIN_COMPANY = '/admin/companies',
  CHAT_INDEX = '/chat',
  CHAT_MESSAGE = '/chat/:to',
}
